name: Docker

on:
  push:
    branches: [main,develop]
  release:
    types: [published]

permissions:
  packages: write
  contents: read

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/hungry-beetle-core-nrt
  VERSION: latest

jobs:
  push:
    name: Push image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: convert image name to lower case
        run: echo "IMAGE_NAME_LC=${IMAGE_NAME,,}" >>${GITHUB_ENV}
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME_LC
      - name: Push image
        run: |
          docker tag $IMAGE_NAME_LC $IMAGE_NAME_LC:$VERSION
          docker push $IMAGE_NAME_LC:$VERSION
